---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document: 
    keep_md: true
---


## Loading and preprocessing the data
```{r loading}
unzip(zipfile="repdata_data_activity.zip")
dat <- read.csv("activity.csv")
summary(dat)
head(dat)
str(dat)
dat$date <- as.Date(dat$date, format="%Y-%m-%d")
```


## What is mean total number of steps taken per day?
```{r}
q1 <- with(dat,tapply(steps,date,sum,na.rm=TRUE))
hist(q1,
	main="Total number of Steps per Day",
	xlab="Total Steps",ylab="Frequency",
	col="red")
mean(q1)
median(q1)
```


## What is the average daily activity pattern?
```{r}
aveSteps <- with(dat, tapply(steps,interval,mean,na.rm=TRUE))
interval <- unique(dat$interval)
dat2 <- data.frame(cbind(interval,aveSteps))
library(ggplot2)
ggplot(data = dat2,aes(x = interval,y = aveSteps))+
	geom_line(color="red")+
	ggtitle("Average Steps per Interval") + xlab("Interval") + ylab("Average Steps")
dat2[which.max(dat2$aveSteps),1]
```


## Imputing missing values
```{r}
sum(is.na(dat$steps))
index <- which(is.na(dat$steps))
len <- length(which(is.na(dat$steps)))
aveSteps2 <- with(dat, tapply(steps,date,mean,na.rm=TRUE))
valuetoreplace <- mean(with(dat,tapply(steps,date,mean,na.rm=TRUE)),na.rm = TRUE)
for (i in 1:len) {
        dat[index[i],1] <- valuetoreplace 
}
new <- with(dat,tapply(steps,date,sum,na.rm=TRUE))
hist(new,
	main="Total number of Steps per Day",
	xlab="Total Steps",ylab="Frequency",
	col="green")
mean(new)
median(new)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
library(dplyr)
newdat <- mutate(dat, day=ifelse(weekdays(dat$date)=="Saturday" | weekdays(dat$date)=="Sunday","weekend","weekday"))
newdat$day<-as.factor(newdat$day)
library(lattice)
stepsByDay <- with(newdat,aggregate(steps ~ interval + day, newdat, mean))
xyplot(steps ~ interval | day, stepsByDay , type = "l", layout = c(1, 2), 
    xlab = "Interval", ylab = "Number of steps")

```
